name: application
on: [push, workflow_dispatch]
env:
 status: Deployment completed
jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Lint code
        run: npm run lint  
  test:
    needs: app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build application
        run: npm run build
      - name: Upload artifact
        uses:  actions/upload-artifact@v4
        with:
          name: dist-file
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v5
        with:
          name: dist-file
      - name: Output files
        run: ls
      - name: Deploy application
        run: echo "Deploying application..."    
  output:      
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: output
        run: echo "$status"
